homeaccounting/urls.py
from django.contrib import admin
from django.urls import path
#from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, SignUpView
from finance.views import MyLoginView, base, home, create_transaction,signup, logout_view, edit_transaction, delete_transaction, filter_transactions
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
   # path('register/', SignUpView.as_view(), name='register'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('', base, name='base'),
    path('home/', home, name='home'),
    path('create_transaction/', create_transaction, name='create_transaction'),
    path('filter_transactions/', filter_transactions, name='filter_transactions'),
    path('transactions/<int:pk>/edit/', edit_transaction, name='edit_transaction'),
    path('delete/<int:pk>/', delete_transaction, name='delete_transaction'),
    path('signup/', signup, name='signup'),
]

finance/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser, Group, Permission
from django.db.models import Sum
from decimal import Decimal
from django.utils import timezone
from datetime import date
from django.contrib.auth import get_user_model


class Category(models.Model):
    CATEGORIES = (
        ('ED', 'Еда'),
        ('HR', 'Хозяйственные расходы'),
        ('CU', 'Коммунальные услуги'),
        ('OO', 'Одежда/обувь'),
        ('RV', 'Развлечения'),
        ('BT', 'Бытовая техника'),
        ('TR', 'Путешествия'),
        ('OT', 'Другое'),
    )
    CATEGORIES_INCOME = (
        ('SAL', 'Зарплата'),
        ('INV', 'Инвестиции'),
        ('GIF', 'Подарки'),
        ('OTH', 'Другое'),
    )

    name = models.CharField(max_length=255)
    expense_category = models.BooleanField(default=True)
    income_category = models.BooleanField(default=False)


    def get_transactions(self):
        return self.transaction_set.all()

    def __str__(self):
        return self.name


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.user.username} - {self.balance}"

    def get_current_balance(self):
        start_date = date.min  # начало периода - минимальная дата
        end_date = date.today()  # конец периода - сегодняшняя дата
        return self.get_total_balance(start_date, end_date)

    def get_total_balance(self):
        transactions = Transaction.objects.filter(account=self)
        total_income = transactions.filter(transaction_type='income').aggregate(Sum('amount'))['amount__sum']
        print("total_income", total_income)
        total_expense = transactions.filter(transaction_type='expense').aggregate(Sum('amount'))['amount__sum']
        print("total_expense", total_expense)
        total_income = total_income if total_income is not None else 0
        total_expense = total_expense if total_expense is not None else 0
        total_balance = total_income - total_expense
        return total_balance



class Transaction(models.Model):
    TRANSACTION_TYPES = (
        ('IN', 'Дохід'),
        ('OUT', 'Витрати'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    description = models.CharField(max_length=255, blank=True)
    date = models.DateField(default=timezone.now)
    transaction_type = models.CharField(max_length=3, choices=TRANSACTION_TYPES)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    difference = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return f"{self.user} {self.transaction_type} {self.amount} ({self.category}) [{self.date.strftime('%d.%m.%Y')}]"

    def save(self, *args, **kwargs):
        # попытка автоматического определения категории
        #print(f"Selected category: {self.category}")
        #self.category = self._get_category()

        # если категория не определена, запрашиваем ее у пользователя
        #if self.category is None:
            #self.category = self._ask_for_category()

        # если пользователь не выбрал категорию, то используем категорию "Другое"
        #if self.category is None:
            #self.category = Category.objects.get(name='Другое')

        if not self.account:
            user = self.user
            try:
                account = Account.objects.get(user=user)
            except Account.DoesNotExist:
                account = Account.objects.create(user=user)
            self.account = account
        super().save(*args, **kwargs)


    def _get_category(self):
        # определение категории на основе правил
        # например, если описание транзакции содержит "еда", то относим ее к категории "Еда"
        if 'еда' in self.description.lower():
            return Category.objects.get(name='Еда')
        # если не удалось определить категорию, то возвращаем None
        return None
"""
    def input_select(message, choices):
        
        Выводит сообщение и предоставляет пользователю выбрать опцию из списка.
        Возвращает идентификатор выбранной опции.

        :param message: Сообщение для вывода пользователю.
        :param choices: Список вариантов. Каждый элемент должен быть кортежем (id, name).
        :return: Идентификатор выбранной опции.
        
        while True:
            print(message)
            for choice in choices:
                print('  {}. {}'.format(choice[0], choice[1]))

            choice_id = input('Введите номер выбранной категории: ')
            try:
                choice_id = int(choice_id)
                if choice_id in [choice[0] for choice in choices]:
                    return choice_id
            except ValueError:
                pass

            print('Некорректный выбор. Попробуйте снова.')


    def _ask_for_category(self):
        # запрашиваем у пользователя категорию для транзакции
        categories = Category.objects.all()
        category_choices = [(category.id, category.name) for category in categories]
        category_choices.append(('other', 'Другое'))
        message = 'Выберите категорию для транзакции "{}":\n'.format(self.description)
        category_id = input_select(message, category_choices)

        if category_id is None:
            return Category.objects.get(name='Другое')
        if category_id == 'other':
            category_name = input_text('Введите название категории: ')
            return Category.objects.create(name=category_name)
        else:
            return Category.objects.get(id=category_id)
"""





class User(models.Model):

    def get_income(self, start_date, end_date):
        # Получаем сумму всех входящих транзакций за указанный период
        income = self.transactions.filter(
            transaction_type='IN', date__range=[start_date, end_date]
        ).aggregate(Sum('amount'))['amount__sum']
        return Decimal(income) if income is not None else Decimal('0.00')

    def get_expenses(self, start_date, end_date):
        # Получаем сумму всех исходящих транзакций за указанный период
        expenses = self.transactions.filter(
            transaction_type='OUT', date__range=[start_date, end_date]
        ).aggregate(Sum('amount'))['amount__sum']
        return Decimal(expenses) if expenses is not None else Decimal('0.00')

    def get_balance(self):
        # Получаем текущий баланс пользователя
        account = Account.objects.get(user=self)
        return account.balance


    def get_expenses_by_category(self, start_date, end_date):
        expenses_by_category = self.transactions.filter(
            transaction_type='OUT', date__range=[start_date, end_date]
        ).values('category__name').annotate(Sum('amount'))

        # Преобразуем результат в список кортежей (категория, сумма)
        return [(item['category__name'], item['amount__sum']) for item in expenses_by_category]

    def get_transactions_by_date_range(self, start_date, end_date):
        return self.transactions.filter(date__range=[start_date, end_date])

# class User(AbstractUser):
#     phone = models.CharField(max_length=20)
#     first_name = models.CharField(max_length=30)
#     last_name = models.CharField(max_length=30)
#
#     class Meta:
#         swappable = 'AUTH_USER_MODEL'

# User.groups.field.related_name = 'finance_user_set'
# User.user_permissions.field.related_name = 'finance_user_set'

finance/forms.py
from django import forms
from .models import Transaction, Category
from django.forms.widgets import SelectDateWidget, Select
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import F

class CustomSelectWidget(Select):
    def optgroups(self, name, value, attrs=None):
        groups = super().optgroups(name, value, attrs)

        for group in groups:
            group_name, group_html, group_values = group

            print(f"Group name: {group_name}")
            print(f"Group HTML: {group_html}")
            print(f"Group values: {group_values}")

        return groups


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class TransactionForm(forms.ModelForm):
    #transaction_type = forms.ChoiceField(choices=Transaction.TRANSACTION_TYPES, label='Тип транзакції')

    class Meta:
        model = Transaction
        fields = ['transaction_type', 'amount', 'description', 'category']

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     # Определите, какой тип транзакции выбран
    #     transaction_type = self.initial.get('transaction_type') or self.data.get('transaction_type')
    #     if transaction_type == 'IN':
    #         # Если выбран тип "Income", используйте список категорий для доходов
    #         self.fields['category'].choices = Category.CATEGORIES_INCOME
    #     else:
    #         # Иначе используйте список категорий для расходов
    #         self.fields['category'].choices = Category.CATEGORIES
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     categories = Category.objects.all()
    #     category_choices = []
    #
    #     for category in categories:
    #         if category.expense_category:
    #             for key, value in Category.CATEGORIES:
    #                 if key == category.name:
    #                     category_choices.append((category.id, value))
    #         elif category.income_category:
    #             for key, value in Category.CATEGORIES_INCOME:
    #                 if key == category.name:
    #                     category_choices.append((category.id, value))
    #
    #     self.fields['category'].choices = category_choices

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        transaction_type = self.initial.get('transaction_type') or self.data.get('transaction_type')
        category_choices = []
        if transaction_type == 'IN':
            # Если выбран тип "Income", используйте список категорий для доходов
            categories = Category.objects.filter(income_category=True)
            categories_model = Category.CATEGORIES_INCOME
        else:
            # Иначе используйте список категорий для расходов
            categories = Category.objects.filter(expense_category=True)
            categories_model = Category.CATEGORIES
        for category in categories:
            for key, value in categories_model:
                if key == category.name:
                    category_choices.append((category.id, value))
        print("transaction_type:", transaction_type)
        print("category_choices:", category_choices)
        self.fields['category'].choices = category_choices


class TransactionFilterForm(forms.Form):
    TRANSACTION_TYPES = [
        ('', 'All'),  # Пустое значение для выбора всех типов
        ('IN', 'Income'),
        ('OUT', 'Expense'),
    ]

    transaction_type = forms.ChoiceField(
        choices=TRANSACTION_TYPES,
        required=False,
        label='Transaction type'
    )

    start_date = forms.DateField(
        label='Start date',
        widget=forms.SelectDateWidget(),
        required=False
    )

    end_date = forms.DateField(
        label='End date',
        widget=forms.SelectDateWidget(),
        required=False
    )

    category = forms.ChoiceField(
        choices=[],
        required=False,
        label='Category'
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].choices = self.get_category_choices()

    def get_category_choices(self):
        transaction_type = self.initial.get('transaction_type') or self.data.get('transaction_type')
        if transaction_type == 'IN':
            category_choices = Category.objects.filter(income_category=True).values_list('id', 'name')
        else:
            category_choices = Category.objects.filter(expense_category=True).values_list('id', 'name')
        choices = [('', 'All')] + list(category_choices)
        return choices

finance/templates/Index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Accounting</title>
    <link rel="stylesheet" href="../style/style.css">
</head>
<body>
<header>
    <div class="header">
        <nav>
            <ul class="menu__list">
                <button class="transaction__btn" id="transaction">Create transaction
                    <span class="arrow"></span></button>
                <li id="open__login">Log in</li>
                <li id="open__register">Registration</li>
            </ul>
        </nav>
    </div>

    <form class="transaction__block" id="transaction__block">
        <div class="menu__trans">
            <label for="type">Transaction type:</label>
            <select id="type">
                <option value="expenses">Expenses</option>
                <option value="income">Income</option>
            </select>
        </div>
        <div class="menu__trans">
            <label for="amount">Amount:</label>
            <input type="number" id="amount">
        </div>
        <div class="menu__trans">
            <label for="description">Description:</label>
            <input type="text" id="description" autocomplete="off">
        </div>
        <div class="menu__trans">
            <label>Category:</label>
            <select id="category__expenses" >
                <optgroup label="Products">
                    <option value="Foodstuff">Foodstuff</option>
                    <option value="Other">Other</option>
                </optgroup>
                <optgroup label="Real estate">
                    <option value="Apartment">Apartment</option>
                    <option value="Communal">Communal</option>
                    <option value="Other">Other</option>
                </optgroup>
                <optgroup label="Entertainment">
                    <option value="Transport">Transport</option>
                    <option value="Internet/Network">Internet/Network</option>
                    <option value="Restaurant/Bar">Restaurant/Bar</option>
                    <option value="Shopping">Shopping</option>
                    <option value="Travel">Travel</option>
                    <option value="Cinema/Theater">Cinema/Theater</option>
                    <option value="Circus/Zoo">Circus/Zoo</option>
                    <option value="Other">Other</option>
                </optgroup>
                <optgroup label="Medical services">
                    <option value="Medical insurance">Medical insurance</option>
                    <option value="Other">Other</option>
                </optgroup>
                <optgroup label="Other expenditure">
                    <option value="Taxes">Taxes</option>
                    <option value="Credit">Credit</option>
                    <option value="Insurance">Insurance</option>
                    <option value="Other">Other</option>
                </optgroup>
            </select>

            <select id="category__income" >
                <option value="Salary">Salary</option>
                <option value="Present">Present</option>
                <option value="Real estate">Real estate</option>
                <option value="Other">Other</option>
            </select>

        </div>
        <div class="menu__trans">
            <label for="date">Date:</label>
            <input type="date" id="date">
        </div>
        <div><button type="submit" class="add__btn">Add</button></div>
    </form>

    <div id="login__modal" class="modal">
        <div class="modal__content">
            <span class="close">&times;</span>
            <h2>Log in</h2>
            <form action="/login" method="POST" class="form__login">
                <input type="email" name="mail" placeholder="Email" class="input" autocomplete="email">
                <span class="error-text"></span>

                <input type="password" name="pass" placeholder="Password" class="input" autocomplete="current-password">
                <span class="error-text"></span>

                <br>
                <input type="submit" value="Log in" class="submit__btn">
            </form>
        </div>
    </div>

    <div id="register__modal" class="modal">
        <div class="modal__content">
            <span class="close">&times;</span>
            <h2>Registration</h2>
            <form action="/login" method="POST" class="form__registration">
                <input type="text" name="username" placeholder="Name" class="input" autocomplete="name">
                <span class="error-text"></span>

                <input type="text" name="surname" placeholder="Surname" class="input" autocomplete="name">
                <span class="error-text"></span>

                <input type="email" name="mail" placeholder="Email" class="input" autocomplete="email">
                <span class="error-text"></span>

                <input type="email" name="confirm-mail" placeholder="Confirm your email" class="input" autocomplete="email">
                <span class="error-text"></span>

                <input type="password" name="pass" placeholder="Password" class="input" autocomplete="new-password">
                <span class="error-text"></span>

                <input type="password" name="confirm-pass" placeholder="Confirm your password" class="input" autocomplete="new-password">
                <span class="error-text"></span>

                <input type="tel" name="phone" placeholder="Phone number +XXXXXXXXX" class="input" autocomplete="phone">
                <span class="error-text"></span>

                <br>
                <input type="radio" name="gender" class="radio">Male
                <input type="radio" name="gender" class="radio">Female
                <br>
                <input type="submit" value="Registration" class="submit__btn">
            </form>
        </div>
    </div>
</header>

<main>
    <div id="body__container"></div>
</main>
<script src="../code/header.js"></script>
<script src="../code/body.js"></script>
</body>
</html>

finance/templates/Sklad.html
<a href="{% url 'home' %}">Главная</a>
<a href="{% url 'transactions' %}">Транзакции</a>
{% if user.is_authenticated %}
<a href="{% url 'logout' %}">Вихід</a>
{% else %}
<a href="{% url 'login' %}">Вхід</a>
{% endif %}

><td><a href="{% url 'edit_transaction' transaction.pk %}">Редагувати</a> | <a href="{% url 'delete_transaction' transaction.pk %}">Видалити</a></td>

<a href="{% url 'home' %}">Головна</a>

finance/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Домашня бухгалтерія{% endblock %}</title>
    </head>
    <body>
    <header>
        <nav>
             <a href="{% url 'login' %}">Вхід</a>
             <a href="{% url 'signup' %}">Реєстрация</a>
         </nav>
     </header>
    <h1>Домашня бухгалтерія</h1>
    <p>Здесь ви маєте змогу вводити свої транзакціії та переглядати список усіх збережених транзакцій.</p>
    {% if error_message %}
    <span class="error-text">{{ error_message }}</span>
    {% endif %}
     <main>
         {% block content %}
         {% endblock %}
     </main>
     </body>
     </html>

finance/templates/create_transaction.html
{% extends 'home.html' %}

{% block content %}
<h1>Створити транзакцію</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
<!--  <select id="id_transaction_type" name="transaction_type">-->
<!--    {% for choice in form.transaction_type.field.choices %}-->
<!--    <option value="{{ choice.0 }}" {% if choice.0 == form.data.transaction_type %}selected{% endif %}>{{ choice.1 }}</option>-->
<!--    {% endfor %}-->
<!--  </select>-->
<!--  &lt;!&ndash; Вывод значений переменных на консоль &ndash;&gt;-->
<!--  {% for category in form.category.field.choices %}-->
<!--    {% if category.0 == form.data.category %}-->
<!--      {{ category.0 }} - {{ category.1 }} <br>-->
<!--    {% endif %}-->
<!--  {% endfor %}-->
<!--  <select id="id_category" name="category">-->
<!--    {% for category in category_choices %}-->
<!--    <option value="{{ category.0 }}" {% if category.0 == form.data.category %}selected{% endif %}>{{ category.1 }}</option>-->
<!--    {% endfor %}-->
<!--  </select>-->
  <button type="submit">Додати</button>
</form>
<!--<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>-->
<!--{% verbatim %}-->
<!--<script>-->
<!--    const transactionTypeSelect = document.querySelector('#id_transaction_type');-->
<!--    const categorySelect = document.querySelector('#id_category');-->
<!--    const categoryChoices = {-->
<!--      'OUT': [-->
<!--        {% for category in expense_category_choices %}-->
<!--          { value: '{{ category.0 }}', label: '{{ category.1 }}' },-->
<!--        {% endfor %}-->
<!--      ],-->
<!--      'IN': [-->
<!--        {% for category in income_category_choices %}-->
<!--          { value: '{{ category.0 }}', label: '{{ category.1 }}' },-->
<!--        {% endfor %}-->
<!--      ]-->
<!--    };-->

<!--    function updateCategoryOptions() {-->
<!--      const selectedType = transactionTypeSelect.value;-->
<!--      const selectedCategories = categoryChoices[selectedType];-->

<!--      categorySelect.innerHTML = '';-->

<!--      for (const category of selectedCategories) {-->
<!--        const option = document.createElement('option');-->
<!--        option.value = category.value;-->
<!--        option.textContent = category.label;-->
<!--        {% if form.data.category %}-->
<!--        if (category.value === '{{ form.data.category }}') {-->
<!--          option.selected = true;-->
<!--        }-->
<!--        {% endif %}-->
<!--        categorySelect.appendChild(option);-->
<!--      }-->
<!--    }-->

<!--    transactionTypeSelect.addEventListener('change', updateCategoryOptions);-->
<!--    updateCategoryOptions();-->
<!--</script>-->
<!--{% endverbatim %}-->
{% endblock %}

finance/templates/edit_transaction.html
{% extends 'home.html' %}

{% block content %}
<h1>Редагувати транзакцію {{ transaction.pk }}</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Зберегти</button>
</form>
{% endblock %}

finance/templates/filter_transactions.html
{% extends 'home.html' %}

{% block content %}
<h2>Фильтрация транзакций</h2>
<form method="GET">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Застосувати фільтр</button>
</form>
{% endblock %}

finance/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
<p>Ви ввійшли як {{ user.username }}. Ваш id - {{ user.id }}.</p>
<a href="{% url 'logout' %}">Вихід</a>
{% endif %}


<a href="{% url 'create_transaction' %}">Створити транзакцію</a>
<a href="{% url 'filter_transactions' %}">Фільтр</a>

{% if transactions %}
<h2>Список транзакцій</h2>
<table>
    <thead>
    <tr>
        <th>Дата</th>
        <th>Тип</th>
        <th>Категорія</th>
        <th>Сума</th>
        <th>Дії</th>
    </tr>
    </thead>
    <tbody>
    {% for transaction in transactions %}
    <tr>
        <td>{{ transaction.date }}</td>
        <td>{{ transaction.transaction_type }}</td>
        <td>{{ transaction.category }}</td>
        <td>{{ transaction.amount }}</td>
        <td><a href="{% url 'edit_transaction' transaction.pk %}">Редагувати</a> | <a href="{% url 'delete_transaction' transaction.pk %}">Видалити</a></td>
    </tr>
    {% endfor %}
    </tbody>
    <p>Баланс: {{ account.balance }}</p>
</table>
<p>Сума відфільтрованих транзакцій: {{ filtered_transactions_sum }}</p>
{% else %}
<p>Транзакції відсутні.</p>
{% endif %}
{% endblock %}

finance/templates/login.html
{% extends 'base.html' %}

{% block content %}
<h2>Авторізація</h2>
<!--<form method="post">-->
<!--    {% csrf_token %}-->
<!--    <label for="username">Ім'я користувача:</label>-->
<!--    <input type="text" name="username" id="username" required>-->
<!--    <br>-->
<!--    <label for="password">Пароль:</label>-->
<!--    <input type="password" name="password" id="password" required>-->
<!--    <br>-->
<!--    <input type="submit" value="Login">-->
<!--</form>-->
<form method="POST" class="form__login">
    {% csrf_token %}
    <input type="email" name="username" id="username" required placeholder="Email" class="input" autocomplete="email">
    <span class="error-text"></span>

    <input type="password" name="password" id="password" required placeholder="Password" class="input" autocomplete="current-password">
    <span class="error-text"></span>

    <br>
    <input type="submit" value="Log in" class="submit__btn">
</form>

<p>ще не зареєстровані? <a href="{% url 'signup' %}">зареєструватись</a>.</p>
<p>Забули пароль? <a href="{% url 'password_reset' %}">Відновлення паролю</a>.</p>

{% if form.non_field_errors %}
<p class="error-message">{{ form.non_field_errors }}</p>
{% endif %}

{% endblock %}

finance/templates/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Відновлення паролю</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Відновити</button>
</form>
{% endblock %}

finance/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<h2>Реєстрація</h2>
<!--<form method="post">-->
<!--  {% csrf_token %}-->
<!--  {{ form.as_p }}-->
<!--  <button type="submit">Зареєструватись</button>-->
<!--</form>-->
<form method="POST" class="form__registration">
  {% csrf_token %}
  <input type="text" name="username" placeholder="Name" class="input" autocomplete="name">
  <span class="error-text"></span>

  <input type="text" name="surname" placeholder="Surname" class="input" autocomplete="name">
  <span class="error-text"></span>

  <input type="email" name="mail" placeholder="Email" class="input" autocomplete="email">
  <span class="error-text"></span>

  <input type="email" name="confirm-mail" placeholder="Confirm your email" class="input" autocomplete="email">
  <span class="error-text"></span>

  <input type="password" name="pass" placeholder="Password" class="input" autocomplete="new-password">
  <span class="error-text"></span>

  <input type="password" name="confirm-pass" placeholder="Confirm your password" class="input" autocomplete="new-password">
  <span class="error-text"></span>

  <!--        <input type="tel" name="phone" placeholder="Phone number +XXXXXXXXX" class="input" autocomplete="phone">-->
  <!--        <span class="error-text"></span>-->

  <input type="submit" value="Registration" class="submit__btn">
</form>
{% endblock %}